config/routes.rb
Rails.application.routes.draw do
  
  get "recipes/" => "recipes#index"
  #this is the welcome page
  get "recipes/" => "recipes#welcome"
  #this is going to create a new recipe
  get "recipes/new" => "recipes#new", as: :new_recipe
  #this is the link to create
  post "recipes/" => "recipes#create"
  #this is the root route to show the recipes
  get "recipes/:id" => "recipes#show", as: :recipe
  #this is the route to edit each specific recipe which can only be accesed from indiviudal recipe s
  get "recipes/:id/edit" => "recipes#edit", as: :edit_recipe
  patch "recipes/:id" => "recipes#update"
  delete "recipes/:id" => "recipes#destroy"
  

  #this is setting the route to users index
  get 'users/' => "users#index"
  #route to return out sign up form
  get 'users/new' => 'users#new', as: :new_user
  #a route to post our user from to
  post 'users/' => 'users#create'


  #this is going to display the new form
  get 'sessions/new' => 'sessions#new', as: :new_session
  #this will create the new session (the login post)
  post 'sessions/new' => 'sessions#create', as: :create_session
  #this will log out the current session
  get "/sessions/destroy" => "sessions#destroy", as: :destroy_session

  # You can have the root of your site routed with "root"
   root 'recipes#welcome'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end
  #get "photos/:id" => "photos#show", as: :photo
  resources :recipes
  resources :photos

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :recipe

  has_attached_file :image, :styles => {
      :original => ['1920x1680>', :jpg],
      :small    => ['100x100#',   :jpg],
      :medium   => ['250x250',    :jpg],
      :large    => ['500x500>',   :jpg]
  }
  
  validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :recipes
	has_secure_password
	
	validates 	:email, presence: :true, length: {in: 6..50 }, uniqueness: { case_sensitive: false}
	
	validates	:password, presence: :true, length: {in: 6..50 }
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end
  def new
    @photo =Photo.new
  end
  def create
    # Find our user that we should attach to
    #@photo = current_user.photos.new(photo_params)
    #or the standard create:
    @photo = Photo.create(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def show

  end

  def photo_params
    params.require(:photo).permit(:image, :photo_date)
  end
end	

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def index
  	@recipes = Recipe.all
  end

  def welcome
  	@recipes = Recipe.all
  end

  def create
  	@recipe = Recipe.new(recipe_params)

  	if @recipe.save
  		redirect_to :recipes
  	else
  		render :new
  	end
  end

  def show
  	@recipe = Recipe.find(params[:id])
  end

  def edit
  	@recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def update
  	@recipe = Recipe.find(params[:id])

  	if @recipe.update_attributes(recipe_params)
  		redirect_to :recipes
  	else
  		render :edit
  	end
  end

  def destroy
  	@recipe = Recipe.find(params[:id])
  	@recipe.destroy
  	redirect_to recipes_path
  end

private
	def recipe_params
		params.require(:recipe).permit(:name, :directions, :ingredients, :avatar)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	#returns a new user for our form inside the new view
	def new
		@user = User.new
	end

	def create
		user = User.where( email: user_params[:email]). first
		if user && user.authenticate(user_params[:password])

			flash[:success] = 'You are signed in!'
			redirect_to recipes_path
		else
			#this redirects back to the page
			flash[:error] = 'Unable to sign you in'

			redirect_to new_session_path
		end
	end

	def destroy
        session[:user_id] = nil
        flash["alert-success"] = "You have logged out"
        redirect_to recipes_path
    end

private
	def user_params
		params.require(:user).permit(:email,:password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index

	end
	#this is going to return our view to register a new user
	def new
		@user = User.new
	end

	def create

      if User.new(user_params).save
        #redicret to signed in
        flash[:success] = 'You are registered'
        redirect_to recipes_path
      else

        flash[:error] = 'registration has failed'

        redirect_to new_session_path

      end
  end
private

  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KitchenSink</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <nav class="navbar navbar-inverse navbar-default">
    <div class="container-fluid">
    <div class="navbar-header">
    <!--  <a class="navbar-brand" rel="home" href="">
        <img style="max-width:55px; margin-top: 0px;"
             src="http://lghttp.16485.nexcesscdn.net/808325/mage/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/p/splg.jpg">
      </a> -->
    <ul class="nav navbar-inverse navbar-nav">

        <li><a href="/recipes">Find A Recipe<span class="sr-only">(current)</span></a>
        </li>
        <li><a href="/recipes/new">Add A Recipe<span class="sr-only">(current)</span></a>
        </li>
        <li><a href="/sessions/new">Log In<span class="sr-only">(current)</span></a>
        </li>
        <li><a href="/sessions/destroy">Log Out<span class="sr-only">(current)</span></a>
        </li>
        <li><a href="/users/new">Create An Account<span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
    </li></ul></div>
 <!--   <form class="navbar-form navbar-right" role="search">
 <div class="form-group">
    <input type="text" class="form-control" placeholder="Search">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
  <button type="button" link="sessions/new" class="btn btn-default navbar-btn">Sign in</button> 
</form> -->



  </div>
</nav>
 <!--  <nav class="navbar navbar-default">
  <div class="container-fluid"> -->
    <!-- Brand and toggle get grouped for better mobile display -->
 <!--  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div> -->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<% @photos.each do |photo| %>

<% end %>

app/views/photos/new.html.erb
<h1>Photos#new</h1>
    <p>Find me in app/views/photos/new.html.erb</p>

    <%= form_for(@photo) do |f| %>
    
      

      <div class="field">
        <%= f.label :image %><br>
        <%= f.file_field :image %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

app/views/recipes/edit.html.erb
<h1>Edit this recipe!</h1>

<%= form_for @recipe do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :directions %>
        <%= f.text_field :directions %>
    </div>

    <div>
        <%= f.label :ingredients %>
        <%= f.text_field :ingredients %>
    </div>

    <%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to "Back to the list!", recipes_path %>

app/views/recipes/index.html.erb
 <div class="container">

        <div class="row">
     
            <div class="col-lg-3 col-md-4 col-xs-6 medium">
                <a class="thumbnail" href="recipes/3">
                    <img class="img-responsive" src="http://healthfoodlover.com/hfl/wp-content/uploads/2010/10/fermented-buckwheat-pancakes-with-black-cuurants-and-cultured-butter-2-wm530.jpg" alt="" style="min-height:50px;height:300px;width:300px">

                </a>
			

            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 medium">
                <a class="thumbnail" href="recipes/4">
                    <img class="img-responsive" src="http://i.huffpost.com/gen/1420805/images/o-POACHED-EGG-facebook.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 medium">
                <a class="thumbnail" href="recipes/5">
                    <img class="img-responsive" src="http://static1.squarespace.com/static/510a909be4b05323be125d3b/t/52e84061e4b025ba0ef057ae/1390952558352/Almond+Berry+Vegan+Overnight+Oats" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 medium">
                <a class="thumbnail" href="recipes/6">
                    <img class="img-responsive" src="http://www.runningwithtweezers.com/wp-content/uploads/2010/10/RoastedTomatoAvocadoFinal.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 medium">
                <a class="thumbnail" href="recipes/7">
                    <img class="img-responsive" src="http://i.huffpost.com/gen/942265/images/o-FENNEL-SALAD-RECIPE-facebook.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 medium">
                <a class="thumbnail" href="recipes/9">
                    <img class="img-responsive" src="http://i.telegraph.co.uk/multimedia/archive/01112/fpear_1112124c.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="recipes/10">
                    <img class="img-responsive" src="http://graphics8.nytimes.com/images/2011/01/12/dining/12mini-span/12mini-span-articleLarge.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="recipes/11">
                    <img class="img-responsive" src="http://foodnetwork.sndimg.com/content/dam/images/food/fullset/2012/11/12/0/FN_FN-Kitchens-Fettuccine-Alfredo_s4x3.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="recipes/12">
                    <img class="img-responsive" src="http://www.gimmesomeoven.com/wp-content/uploads/2012/06/roasted-beet-arugula-goat-cheese-and-honey-crostini.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="recipes/13">
                    <img class="img-responsive" src="http://callhimyeschef.files.wordpress.com/2012/05/blackberry-cobbler-49-edit-web.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="recipes/14">
                    <img class="img-responsive" src="http://api.ning.com/files/kV4MbYiv7oTdw50YnzzvfpFS0dg3*1uLbVMaZQi757bgcFkIgiM6NShiWAZvQQLMua2QdOrzwj02LQQS-z0Cu1omrmwJqYR1/1082023356.jpeg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="recipes/15">
                    <img class="img-responsive" src="http://liveloveeatraw.com.au/wp-content/uploads/2014/04/photo1-6.jpg" alt="" style="min-height:50px;height:300px;width:300px">
                </a>
            </div>
        </div>
	</div>
	<div>

<h1>Today's Recipes</h1>

<ul>
    <% @recipes.each do |recipe| %>
        <li>
            <strong> <%= recipe.name %> </strong> - <%= recipe.directions %> 
         <%= link_to "More Info", recipe_path(recipe) %>  
        </li>
        
    <% end %>
</ul>
		
		<strong><%= link_to "Add A Recipe", new_recipe_path %></strong>
	</div>

app/views/recipes/new.html.erb
<h1>Add a new recipe!</h1>

<%= form_for @recipe do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="form group form-group-lg">
        <%= f.label :directions %>
    <div class="textbox">
        <%= f.text_field :directions, :size => "50x30"%>
    </div>
    </div>

    <div class="form group form-group-lg">
        <%= f.label :ingredients %>
        <%= f.text_field :ingredients %>
    </div>
   
    

    <%= f.submit "Add new recipe!" %>


<%= link_to "Back to the list!", recipes_path %>

<% end %>

app/views/recipes/show.html.erb
<h1> <%= @recipe.name %> </h1>

<p>This recipe is for <%= @recipe.name %> and you need to <%= @recipe.directions %>, and you will need <%= @recipe.ingredients %> in order to make it.</p>


<%= link_to "Edit this recipe.", edit_recipe_path(@recipe) %>
<%= link_to "Back to the list!", recipes_path %>
<%= link_to "Delete this recipe!", recipe_path, method: :delete, data: { confirm: "Are you sure you want to delete this recipe?"} %>

app/views/recipes/welcome.html.erb
<header class="image-bg-fluid-height">
        
</header>
	<strong><h3 class="welcome-header text-center">Welcome</h3></strong>
	<strong><h5 class="welcome-header text-center">to</h5></strong>
	<strong><h1 class="welcome-header text-center">Spatula</h1></strong>
	<strong><p class="welcome-header text-center">We are dedicated to bringing you the healthy, delicious, seasonal farm to table recipes week after week. It is our mission to make the world a better and healthier place one plate at a time. We hope you enjoy our recipes and that you will share your own with your fellow community.</p></strong>
<header class="image-bg-fluid-heights">
<header class="image-bg-fluid-heighter">




 

app/views/users/new.html.erb
    <%= form_for(@user) do |f| %>
	
      <% flash.each do |key,value|  %>
        <div class="<%= key %>" > <%= value %> </div>
      <% end %>
	
      <%= f.label :email %>
      <%= f.email_field :email %>
	
      <%= f.label :password %>
      <%= f.password_field :password %>
	
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
	
      <%= f.submit "Signup" %>
      
    <% end %>